apiVersion : apps/v1
kind: Deployment
metadata:
  name: "demoakscluster-69db"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demoakscluster-69db"
  template:
    metadata:
      labels:
        app: "demoakscluster-69db"
    spec:
      containers:
        - name: "demoakscluster-69db"
          image: "barutacr.azurecr.io/demoakscluster"
          ports:
          - containerPort: 80