apiVersion: v1
kind: Service
metadata:
    name: "demoakscluster-69db"
    labels:
        app: "demoakscluster-69db"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "demoakscluster-69db"