apiVersion: v1
kind: Service
metadata:
    name: "demoaks-e3dc"
    labels:
        app: "demoaks-e3dc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "demoaks-e3dc"