on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tatacr.azurecr.io
        username: ${{ secrets.acr_tatacr_username }}
        password: ${{ secrets.acr_tatacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "dockerfile" -t tatacr.azurecr.io/demoaks:${{ github.sha }} --label dockerfile-path=dockerfile
        docker push tatacr.azurecr.io/demoaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demoaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demoaks9ec8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demoaks9ec8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demoaks9ec8
        container-registry-url: tatacr.azurecr.io
        container-registry-username: ${{ secrets.acr_tatacr_username }}
        container-registry-password: ${{ secrets.acr_tatacr_password }}
        secret-name: demoaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demoaks9ec8
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          tatacr.azurecr.io/demoaks:${{ github.sha }}
        imagepullsecrets: |
          demoaksdockerauth
